"use client"
import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import SessionProviderComp from '@/components/nextauth/SessionProvider'
import {ContentManageProvider} from '@/app/context/ContentManageContext'
import { usePathname } from 'next/navigation'
import { Suspense } from 'react'

const font = Bricolage_Grotesque({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'ATM',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode
  session: any
}>) {

  const pathname = usePathname();

  const hideHeaderFooter = pathname.startsWith("/content");
  const SininPage = pathname.startsWith("/signin");
  return (
    <html lang='en'>
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#07be8a" />
         <ContentManageProvider>
        <SessionProviderComp session={session}>
          <Suspense>
          <ThemeProvider
            attribute='class'
            enableSystem={true}
            defaultTheme='light'>
              {!hideHeaderFooter && !SininPage ? <Header />:false}
              {children}
             {!hideHeaderFooter && !SininPage ? <Footer />: false}
          </ThemeProvider>
          </Suspense>
        </SessionProviderComp>
         </ContentManageProvider>
      </body>
    </html>
  )
}
