"use client"
import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import SessionProviderComp from '@/components/nextauth/SessionProvider'
import { ContentManageProvider } from '@/app/context/ContentManageContext'
import { usePathname } from 'next/navigation'
import { Suspense } from 'react'
import Script from 'next/script'

const font = Bricolage_Grotesque({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'ATM',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode
  session: any
}>) {

  const pathname = usePathname();

  const hideHeaderFooter = pathname.startsWith("/content");
  const SininPage = pathname.startsWith("/signin");
  
  // ✅ Add both pages here to hide Header/Footer
  const projectManagementPage =
  pathname === "/projectmanagementstartups" ||
  pathname === "/projectmanagement" ||
  pathname === "/projectmanagementcommunities";



  return (
    <html lang='en'>
      <head>
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-DVX38ML9PE"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-DVX38ML9PE');
          `}
        </Script>
      </head>
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#07be8a" />
        <ContentManageProvider>
          <SessionProviderComp session={session}>
            <Suspense>
              <ThemeProvider
                attribute='class'
                enableSystem={true}
                defaultTheme='light'
              >
                {/* ✅ Hide Header on selected pages */}
                {!hideHeaderFooter && !SininPage && !projectManagementPage ? <Header /> : false}

                {children}

                {/* ✅ Hide Footer on selected pages */}
                {!hideHeaderFooter && !SininPage && !projectManagementPage ? <Footer /> : false}
              </ThemeProvider>
            </Suspense>
          </SessionProviderComp>
        </ContentManageProvider>
      </body>
    </html>
  )
}
